### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by KirbyYT** [ZayBlockBugLine/ZayBlockBugLine#1]
Pls Unban me I was Admin And i put tnt in a small area then zaydenxm the Owner banned me for "The Ban Hammer Has Spoken" i was not supposed to be banned because this is not on the rules pls consider this.

**Comment by KirbyYT** [comment]
I was in Admin and i did that because the village was ugly

**Comment by ZayBlockBugLine** [comment]
Hey User Kirby_YT How May I Help You....

**Comment by ZayBlockBugLine** [comment]
I see You Where banned on zayblock right???

**Comment by ZayBlockBugLine** [comment]
Why Did You Do That

**Comment by KirbyYT** [comment]
I think i should be unbanned because this is the server that i've known for a really really long time

**Comment by ZayBlockBugLine** [comment]
Ok, Why Should You Be Unbaned, Knowing the server for a long time is not why??

**Comment by KirbyYT** [comment]
if you could give me a second chance, I'd stop abusing my rank in which i didn't do.

**Comment by ZayBlockBugLine** [comment]
Kirby_YT Last Report on you said that you where using world edit on Skyblock and sometimes messing up the owners builds???

**Comment by ZayBlockBugLine** [comment]
The Last Person that reported you was, 269Grimawesome Kirby_YT and Jxawsome...

**Comment by KirbyYT** [comment]
I was never reported and i never did that pls consider you are not being fair to an innocent player
i would like to be unbanned my friend is waiting for me

**Comment by ZayBlockBugLine** [comment]
Excuse me yes u did....

**Comment by ZayBlockBugLine** [comment]
And give more detail...... If you lie this post will be closed

**Comment by KirbyYT** [comment]
Im not lying

**Comment by KirbyYT** [comment]
pls unban me

**Comment by ZayBlockBugLine** [comment]
One More reason why??

**Comment by KirbyYT** [comment]
Because ill be more respectful this time

**Comment by ZayBlockBugLine** [comment]
ThankYou Kirby_YT!!!
You Will Be **UNABANED** in 24hours Or less
When Your Unbaned this post will be closed!!!
This post will be locked for now,
Anymore appeals create a new one!!!

**Comment by ZayBlockBugLine** [comment]
Make Sure To Keep looking on this post so keep it in a tab!!!
