### ISSUE TITLE
Staff Appeal

### ISSUE THREAD

**Issue by KirbyYT** [ZayBlockBugLine/ZayBlockBugLine#10]
i want head-admin back because i want to help the server in many way such as building breaking
and banning hackers. When i go onto the server next time please unjail me. 

                                                                Your Mod,
                                                                 Luke M.

**Comment by ZayBlockBugLine** [comment]
Ok c+
![image](https://user-images.githubusercontent.com/30163085/28638998-a0d64bb4-7214-11e7-9524-53aa60c5f70b.png)

**Comment by ZayBlockBugLine** [comment]
more detail

**Comment by ZayBlockBugLine** [comment]
Preview

more detail
more detail
