### ISSUE TITLE
Admin appeal

### ISSUE THREAD

**Issue by KirbyYT** [ZayBlockBugLine/ZayBlockBugLine#4]
i want to apply for admin

**Comment by ZayBlockBugLine** [comment]
Hey Welcome To Zayblock Appeal Line!!!!

Why Do You Want to be Admin???

**Comment by KirbyYT** [comment]
so i can help the server

**Comment by ZayBlockBugLine** [comment]
------------------------------------------------WELCOME NEW ADMIN----------------------------------------
READ
As admin You Need To Know All Default Rules!!!! If You See Staff Abusing there powers please tell me!!!!
As admin Your Not Allowed To abuse Your Powers, Are Server Is A little different You can ban any hacker when you need to.... you dont need to tell an owner or a Sr.Mod...... All bans please email me asap.... tho..... Thank You!!!!
As admin Your Tag Will Be admin~"PLAYERNAME" FYI THE color of your role can change!!!
As admin You Can Quit You Job In A Week..... WARNING!!!! QUITING YOU JOB MAKES YOU SO YOU CANT RE-APPLY FOR MOD IN 2 Months.... If Try Re applying during that time you will be declined and you account will be banned from the server for 1 year and you cant reapply for 1 year!!!!!!!!
If Your account is false banned as a mod you email me that you where banned and i will unban you asap!!!

**Comment by KirbyYT** [comment]
OK i agree
