### ISSUE TITLE
Why Do You Want To Be Banned 269GrimAwesome

### ISSUE THREAD

**Issue by KirbyYT** [ZayBlockBugLine/ZayBlockBugLine#7]

**Comment by ZayBlockBugLine** [comment]
hi

**Comment by ZayBlockBugLine** [comment]
I want to be unbaned because someone trolled be to be banned!!!!

**Comment by KirbyYT** [comment]
Y'all can't handle this
Y'all don't know what's about to happen baby
Team 10
Los Angeles, Cali boy
But I'm from Ohio though, white boy

[Verse 1: Jake Paul]
It's everyday bro, with the Disney Channel flow
5 mill on YouTube in 6 months, never done before
We pass all the competition man, PewDiePie is next
Man I'm poppin' all these checks, got a brand new Rolex
And I met a Lambo too and I'm coming with the crew
This is Team 10, bitch, who the hell are flippin' you?
And you know I kick them out if they ain't with the crew
Yeah, I'm talking about you, you beggin' for attention
Talking shit on Twitter too but you still hit my phone last night
It was 4:52 and I got the text to prove
And all the recordings too, don't make me tell them the truth
And I just drop some new merch and it's selling like a god, church
Ohio is where I'm from, we chew 'em like it's gum
We shooting with a gun, the tattoo just for fun
I Usain Bolt and run, catch me at game one
I cannot be outdone, Jake Paul is number one

[Chorus: Jake Paul]
It's everyday bro
It's everyday bro
It's everyday bro
I said it is everyday bro!

**Comment by KirbyYT** [comment]
[Verse 2: Nick Crompton]
You know it's Nick Crompton and my collar stay poppin'
Yes, I can rap and no, I am not from Compton
England is my city
And if it weren't for Team 10, then the US would be shitty
I'll pass it to Chance 'cause you know he stay litty

[Verse 3: Chance Sutton]
Two months ago you didn't know my name
And now you want my fame? Bitch I'm blowin' up
I'm only going up, now I'm going off, I'm never fallin' off
Like Mag, who? Digi who? Who are you?
All these beefs I just ran through, hit a milli in a month
Where were you? Hatin' on me back in West Fake
Think you need to get your shit straight
Jakey brought me to the top, now we're really poppin' on
Number 1 and number 4, that's why these fans all out the door
It's lonely at the top so we all going
We left Ohio, now the trio is all rollin'
It's Team 10, bitch
We back again, always first, never last
We the future, we'll see you in the past

[Chorus: Jake Paul]
It's everyday bro
It's everyday bro
It's everyday bro
I said it is everyday bro!
