### ISSUE TITLE
Ban Apeall

### ISSUE THREAD

**Issue by KirbyYT** [ZayBlockBugLine/ZayBlockBugLine#8]
i just wanted to say sorry
i would like to be banned
pls unban me pls grim i know thats you reading this
and if you do well
you both were always mean to me :)
i just wanted to say Unban me
apologie accepted????

**Comment by KirbyYT** [comment]
Hello

**Comment by ZayBlockBugLine** [comment]
Hi User Kirby_YT Why Where You Banned In The First Place????

**Comment by KirbyYT** [comment]
because i broke the rules

**Comment by ZayBlockBugLine** [comment]
Why Did You??

**Comment by KirbyYT** [comment]
because james was being mean

**Comment by ZayBlockBugLine** [comment]
Give Me 2 More Resons

**Comment by KirbyYT** [comment]
he told me to shutup and he muted me for nothing

**Comment by ZayBlockBugLine** [comment]
Your Ban Appeal Has Been DECLINED!!!! 

Try Again Or.... Quit!!!
