### ISSUE TITLE
UNBAN ME

### ISSUE THREAD

**Issue by KirbyYT** [ZayBlockBugLine/ZayBlockBugLine#9]
i just wanted to say sorry
i would like to be banned
pls unban me pls grim i know thats you reading this
and if you do well
you both were always mean to me :)
i just wanted to say Unban me
apologie accepted????

**Comment by KirbyYT** [comment]
i  broke the rules

**Comment by KirbyYT** [comment]
im sorry for breaking them

**Comment by KirbyYT** [comment]
unban me

**Comment by KirbyYT** [comment]
pls

**Comment by KirbyYT** [comment]
just pls unban me

**Comment by KirbyYT** [comment]
HELLO

**Comment by ZayBlockBugLine** [comment]
OK... Dont Bully james Anymore!!!

**Comment by KirbyYT** [comment]
WHYA RE YOU TAKING SO LONG ANSWER

**Comment by KirbyYT** [comment]
PLS

**Comment by KirbyYT** [comment]
i want to be unabnned

**Comment by ZayBlockBugLine** [comment]
OK... Dont Bully james Anymore!!!

**Comment by KirbyYT** [comment]
wow he bullied me

**Comment by ZayBlockBugLine** [comment]
YOUR ACCEPTED!!!!!
YOU WILL BE UNBANED 1-5 MIN

**Comment by KirbyYT** [comment]
i was nic eto him
